config/routes.rb
Comparify::Application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  root "pages#home"

  get 'autocomplete_topic_tags', to: "topics#autocomplete_tag"
  resources :topics, only: [:index, :new, :create, :show] do
    resources :answers, only: [:create, :new]
  end

  resources :answers do
    resources :comments, shallow: true
  end
  resources :comments, only: [:show, :edit, :update, :destroy]

  resources :users
  resources :relationships
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  include PublicActivity::Common
  extend FriendlyId

  before_save :downcase_attributes
  belongs_to :user
  belongs_to :category, counter_cache: true
  has_many :answers, dependent: :destroy

  validates :first_subject, presence: true
  validates :second_subject, presence: true
  validates :question, presence: true,
            uniqueness: {scope: [:first_subject, :second_subject],
            case_sensitive: false, message: "Someone already asked this exact question, go figure"}
  validate :has_different_subjects

  friendly_id :subjects_with_question, use: :slugged
  acts_as_taggable

  def user_already_answered?(user)
    answers.where(user_id: user.id).empty?
  end


  private
  def subjects_with_question
    "#{first_subject}-versus-#{second_subject}-#{question}"
  end

  def downcase_attributes
    self.first_subject = self.first_subject.downcase
    self.second_subject = self.second_subject.downcase
    self.question = self.question.downcase
  end

  def has_different_subjects
    if self.first_subject && self.second_subject && self.first_subject.downcase == self.second_subject.downcase
      errors[:base] << "subjects for comparisson can't be the same"
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    if params[:tag]
      @topics = Topic.tagged_with(params[:tag])
    else
      @topics = Topic.all
    end
  end

  def new
    @topic = Topic.new
  end

  def show
    @first_subject_answers = @topic.answers.supports_first_subject
    @second_subject_answers = @topic.answers.supports_second_subject
    @answer = Answer.new
    @tags = @topic.tag_list
  end

  def create
    @topic = current_user.topics.build(topic_params)
    @topic.tag_list.add(params[:tag_list], parse: true) if params[:tag_list]
    if @topic.save
      @topic.create_activity :create, owner: current_user
      redirect_to @topic, notice: "Done, now let's sit and wait for answers..."
    else
      render action: 'new'
    end
  end

  def autocomplete_tags
    redirect_to home_path
  end

  private

  def set_topic
    @topic ||= Topic.friendly.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:first_subject, :second_subject, :question, :category_id)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper

  def new_answer_link(subject)
    title = subject == :first ? @topic.first_subject.titleize : @topic.second_subject.titleize
    link_class = subject == :first ? 'btn btn-primary' : 'btn btn-info'
    tooltip_placement = subject == :first ? 'left' : 'right'
    if current_user && is_topic_owner?
      link_for_voting(title: title, path: "#", opt: {id: "#{subject.to_s}_subject_button",
                                                     'data-placement' => tooltip_placement,
                                                     'data-title' => "Well, you can't answer your own question!",
                                                     :class => link_class})
    elsif user_already_voted?
      link_for_voting(title: title, path: "#", opt: {id: "#{subject.to_s}_subject_button",
                                                     'data-placement' => tooltip_placement,
                                                     'data-title' => "You already answerred this question, can't do it twice",
                                                     :class => link_class})
    elsif current_user
      link_for_voting(title: title, path: '#answer-modal', opt: {:remote => true,
                                                                 'data-toggle' =>  "modal",
                                                                 'data-target' => '#answer-modal',
                                                                 'data-subject' => subject.to_s,
                                                                 :class => link_class})
    else
      link_for_voting(title: title, path: new_user_session_path, opt: {id: "#{subject.to_s}_subject_button",
                                                                       'data-placement' => tooltip_placement,
                                                                       'data-title' => "Click to Login first!",
                                                                       :class => link_class})
    end
  end

  def voters_for_subjects
    unless @first_subject_answers.empty? && @first_subject_answers.empty?
      capture_haml do
        haml_tag :p do
          unless @first_subject_answers.empty?
            haml_tag :span, pluralize("#{@first_subject_answers.count}", "voter"), {:class => 'label label-primary pull-left'}
          end
          unless @second_subject_answers.empty?
            haml_tag :span, pluralize("#{@second_subject_answers.count}", "voter"), {:class => 'label label-info pull-right'}
          end
        end
      end
    end
  end

  def first_subject_answers_count(topic)
    topic.answers.supports_first_subject.count
  end

  def second_subject_answers_count(topic)
    topic.answers.supports_second_subject.count
  end

  def get_topic_owner
    if @topic.user == current_user
      link_to "Me", @topic.user
    else
      link_to @topic.user.name, @topic.user
    end
  end

  def is_topic_owner?
    current_user.topics.include?(@topic)
  end

  def user_already_voted?
    current_user && !@topic.user_already_answered?(current_user)
  end

  def link_for_voting(options={})
    link_to "Your Argument For #{options[:title]}", options[:path], options[:opt]
  end

end

app/views/topics/_form.html.haml
= bootstrap_form_for(@topic) do |f|
  .row
    .col-xs-5
      = f.text_field :first_subject, hide_label: :true
    .col-xs-2.center
      %span.help-block.topic-form Vs
    .col-xs-5
      = f.text_field :second_subject, hide_label: :true
  .form-group
    = f.text_area :question, rows: 4
  .form-group
    = f.collection_select :category_id, Category.all.order("name ASC"), :id, :name
  .form-group{"data-no-turbolink" => ""}
    = label_tag "Add Some Tags (User Enter Key)"
    = text_field_tag :tag_list, nil, :data => {:role => "tagsinput"}
  = f.submit "Go Ahead Ask The Crowd", class: "btn btn-info btn-block"

app/views/topics/_sidebar.html.haml
#sidebar.col-xs-6.col-sm-6.col-md-3.sidebar-offcanvas{role: "navigation"}
  - if @tags.any?
    = render 'sidebar_tags', obj: @tags

  / - if @links.any?
  /   = render 'sidebar_links', obj: @links

app/views/topics/_sidebar_tags.html.haml
.panel.panel-default.sidebar-nav
  .panel-heading
    Tags
  .panel-body
    - @tags.each do |tag|
      = link_to topics_path(tag: tag) do
        %span.label.label-default= tag

app/views/topics/_topic.html.haml
.topic-box.col-xs-12.col-sm-4
  .panel.panel-default
    .panel-heading
      %h3.panel-title.center
        = link_to "#{topic.first_subject} Vs #{topic.second_subject}", topic
    .panel-body
      #{topic.question}
    .panel-footer
      %span.fa.fa-comments= " #{first_subject_answers_count(topic)}"
      %span.fa.fa-comments.fa-flip-horizontal.pull-right
      %span.pull-right= " #{second_subject_answers_count(topic)}"

app/views/topics/index.html.haml
.row
= render @topics

app/views/topics/new.html.haml
.well.col-sm-12.col-md-6.col-sm-offset-3
  %legend.center Help Me Make Up My Mind
  = render 'form'

app/views/topics/show.html.haml
.row.row-offcanvas.row-offcanvas-right
  .col-xs-12.col-sm-12.col-md-9
    %p.pull-right.visible-xs.visible-sm
      %button.btn.btn-primary.btn-xs{"data-toggle" => "offcanvas", type: "button"} Toggle nav
    .jumbotron
      %h2= "#{@topic.first_subject.titleize} Vs #{@topic.second_subject.titleize}"
      %p.lead= @topic.question
      .ui-group-buttons
        = new_answer_link(:first)
        .or.or-lg
        = new_answer_link(:second)
      .p
        %small
          asked by
          = get_topic_owner
      = voters_for_subjects

    .row
      = render partial: 'answers/answers_column', locals: {column: "first", topic: @topic, answers: @first_subject_answers}
      .linetimeline
      = render partial: 'answers/answers_column', locals: {column: "second", topic: @topic, answers: @second_subject_answers}
  = render 'sidebar', locals: {tags: @tags}

#answer-modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "answer-modal-label", role: "dialog", tabindex: "-1"}
  = render 'answers/form'