config/routes.rb
Comparify::Application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  root "pages#home"

  get 'autocomplete_topic_tags', to: "topics#autocomplete_tag"
  resources :topics, only: [:index, :new, :create, :show] do
    resources :answers, only: [:create, :new]
  end

  resources :answers do
    resources :comments, shallow: true
  end
  resources :comments, only: [:show, :edit, :update, :destroy]

  resources :users
  resources :relationships
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include PublicActivity::Common

  belongs_to :user
  belongs_to :topic, counter_cache: true

  validates :body, presence: true
  validates :user_id, :uniqueness => { scope: :topic_id,
                                       message: "You can only have one answer per topic" }

  SUBJECT_HASH = {first: 1, second: 2}
  enum referred_subject: [ :first, :second ]

  scope :supports_first_subject,  -> {where(referred_subject: :first)}
  scope :supports_second_subject, -> {where(referred_subject: :second)}


  # def referred_subject=(subject)
  #   write_attribute(:referred_subject, SUBJECT_HASH[subject.to_sym])
  # end

  # def referred_subject
  #   SUBJECT_HASH.key(read_attribute(:referred_subject))
  # end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include FormatHelper
  before_action :authenticate_user!, except: [:show]

  def create
    @topic = Topic.friendly.find(params[:topic_id])
    @answer = current_user.answers.create(answer_params.merge(topic_id: @topic.id))
    @answer.create_activity :create, owner: current_user if @answer.persisted?
    respond_to do |format|
      format.html { redirect_to @topic }
      format.js
    end
  end

  def destroy

  end

  private

  def answer_params
    params.require(:answer).permit(:body, :referred_subject)
  end
end

app/views/answers/_answer.html.haml
.timeline-badge
.row.clearfix.timeline-panel
  .col-md-3.column
    %img.img-circle{src: "https://gravatar.com/avatar/a9377d333b8aec095a3646bf1799e178?d=https%3A%2F%2Fidenticons.github.com%2F462cf426418db897544f727d569f6fbe.png&r=x"}
    = link_to answer.user.name, answer.user
  .col-md-9.topic-comment
    %p= raw format(answer.body)
  .col-md-12.actions
    %p
      = link_to '#' do
        %i.fa.fa-thumbs-o-up
      %span{:class => "action_text"} vote
      = link_to '#' do
        %i.fa.fa-thumbs-o-down
      %span.actions_divider .
      %i.fa.fa-comments-o{:class => "pull-left"}
      %span= link_to "add comment", new_answer_comment_path(answer), {remote: true, id: answer.id, :class => "pull-left"}
      %span.actions_divider .
      = timeago answer.created_at, {:class => "pull-right timeago"}
%div{:style => "clear:both"}

app/views/answers/_answers_column.html.haml
- if column == "first"
  .col-xs-12.col-sm-6.first_subject_answers{:id => "#{column}_subject_answers"}
    = render partial: "answers/answer", collection: answers
- else
  .col-xs-12.col-sm-6.timeline-inverted.second_subject_answers{:id => "#{column}_subject_answers"}
    = render partial: "answers/answer", collection: answers

app/views/answers/_form.html.haml
= bootstrap_form_for([@topic, @answer], remote: true, style: :vertical) do |f|
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
        %h4#modalLabel.modal-title Ooops, you naughty dude, trying to submit empty answer?
      .modal-body
        = f.alert_message "Please fix the errors below."
        = f.text_area :body, hide_label: true, rows: 4, placeholder: "explain..."
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
        = f.submit "Add Answer", class: "btn btn-primary"

app/views/answers/create.js.haml
-if @answer.valid?
  :plain
    $('form').find('textarea').val("")
    $('#answer-modal').modal('hide')
    var column_selector = "##{@answer.referred_subject.to_s}" + "_subject_answers"
    $(column_selector).append('#{j render @answer}');
    $("abbr.timeago").timeago()

-else
  :plain
    $('#answer-modal').html("#{ j render(partial: 'answers/form', locals: {topic: @topic, answer: @answer}) }");
    var hidden_field = "<input id='answer_referred_subject' name='answer[referred_subject]' type='hidden' value='#{@answer.referred_subject}'>"
    $(".modal-body").append(hidden_field)